name: Build Gradle Hybrid

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@939bdf9b607a5cbcc80c1bed41dd44528b051ee4
    with:
      flow-type: hybrid
      java-version: '11'
