name: Check for artifact and register release

on:
  workflow_run:
    workflows: ["Release Gradle Hybrid"]
    types:
      - completed

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-check-and-register-release.yml@09ed978b979f1362cbbb3d9287aa06ddaa130bfc
    if:  "${{ github.event.workflow_run.conclusion == 'success' }}"
    with:
      artifact-pattern: "octopus-test/_VER_/octopus-test-_VER_.jar"
    secrets: inherit
