name: Check for artifact and register release

on:
  workflow_run:
    workflows: ["Release Gradle Hybrid"]
    types:
      - completed

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-check-and-register-release.yml@d27e77219dc076c1c3129f85c48bd632f165a550
    if:  "${{ github.event.workflow_run.conclusion == 'success' }}"
    with:
      artifact-pattern: "octopus-test/_VER_/octopus-test-_VER_.jar"
    secrets: inherit
