name: Quality Gates

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-quality-gates.yml@8dad627bc0be42f10cd8aba6e733665093865bcb
    with:
      java-version: '21'
