name: Quality Gates

on:
  workflow_call:
  workflow_dispatch:

jobs:
  quality:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-quality-gates.yml@77e7ac6a51809e92405d15f19d8950cfe7baa7e5
    with:
      java-version: '21'
