name: Quality Gates

on:
  workflow_call:
  workflow_dispatch:

jobs:
  quality:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-quality-gates.yml@4aae9166b4df6d7bc810bfd8bd652b8d20fe6bd4
    with:
      java-version: '21'
