name: Release Gradle Hybrid

on:
  repository_dispatch:
    types: release

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@4dc654751b3f1f1d9e0f0fdb677eabd3a1619135
    with:
      flow-type: hybrid
      java-version: '21' 
      commit-hash: ${{ github.event.client_payload.commit }}
      build-version: ${{ github.event.client_payload.project_version }}
      register-release-immediately: true
    secrets: inherit
