name: Release Maven Hybrid

on:
  repository_dispatch:
    types: release-maven

permissions:
  contents: write

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@fd39bd3e6f5b98c0df96a0cd1724d2221450af30
    with:
      flow-type: hybrid
      java-version: '8'
      commit-hash: ${{ github.event.client_payload.commit }}
      build-version: ${{ github.event.client_payload.project_version }}
      register-release-immediately: true
    secrets: inherit
