name: Release Maven Public

on: workflow_dispatch

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@0ff816057055fc3dc6bb0116c0142df18dfe5d5a
    with:
      flow-type: public
      java-version: '21'
    secrets: inherit
