name: Release Gradle Hybrid Docker

on:
  repository_dispatch:
    types: release-docker

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@1ebbbae54ae84d9914b557e973328916b8b5c6e5
    with:
      flow-type: hybrid
      java-version: '21'
      commit-hash: ${{ github.event.client_payload.commit }}
      build-version: ${{ github.event.client_payload.project_version }}
      docker-image: octopus-test
      register-release-immediately: true
      github-packages-publications: bootJava
    secrets: inherit
