name: Release Maven Public

on: workflow_dispatch

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@maven-hybrid-flow
    with:
      flow-type: public
      java-version: '11'
    secrets: inherit
