name: Release Gradle Public

on: workflow_dispatch

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@b41289a460bab00cb467b768eb84c138ce7f7cd4
    with:
      flow-type: public
      java-version: '21'
    secrets: inherit
