name: Release Gradle Public

on: workflow_dispatch

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@dd8c696f48c4143060f68f4d0af4e689004b7cb8
    with:
      flow-type: public
      java-version: '21'
    secrets: inherit
