name: Release Gradle Public

on: workflow_dispatch

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@4aae9166b4df6d7bc810bfd8bd652b8d20fe6bd4
    with:
      flow-type: public
      java-version: '21'
    secrets: inherit
