name: Release Maven Public

on: workflow_dispatch

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@v2.1.7
    with:
      java-version: '11'
    secrets: inherit
