name: Release Maven Hybrid

on:
  repository_dispatch:
    types: release-maven

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@b708046a3cc44d43c13e9aa65d15669b720b7d6e
    with:
      flow-type: hybrid
      java-version: '8'
      commit-hash: ${{ github.event.client_payload.commit }}
      build-version: ${{ github.event.client_payload.project_version }}
      register-release-immediately: true
    secrets: inherit
