name: Release Gradle Hybrid

on:
  repository_dispatch:
    types: release

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@ff80643474de6513cd1c1d538c41438c3d5cf177
    with:
      flow-type: hybrid
      java-version: '21' 
      commit-hash: ${{ github.event.client_payload.commit }}
      build-version: ${{ github.event.client_payload.project_version }}
      register-release-immediately: true
    secrets: inherit
