name: Release Maven Public

on: workflow_dispatch

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@d6cdf0110c8cd4313e2559b245d2af5a2d520f09
    with:
      flow-type: public
      java-version: '21'
    secrets: inherit
