name: Release Gradle Hybrid

on:
  repository_dispatch:
    types: release

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@0a59c1ac4a10209e3b60d1beb8a18aa9830c6674
    with:
      flow-type: hybrid
      java-version: '21' 
      commit-hash: ${{ github.event.client_payload.commit }}
      build-version: ${{ github.event.client_payload.project_version }}
      register-release-immediately: true
    secrets: inherit
