name: Release Maven Public

on: workflow_dispatch

permissions:
  contents: write

jobs:
  release:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@6f66384eb88f8ab49144b556e6fcd5f1973ae3aa
    with:
      flow-type: public
      java-version: '21'
    secrets: inherit
