name: Security Reports

on:
  workflow_call:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  security:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-security-reports.yml@af862a7843894c12c2a3a88569473aecc3172c7a
    with:
      java-version: '21'
      enable-dependency-check: false
