name: Security Reports

on:
  workflow_call:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  security:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-security-reports.yml@8dad627bc0be42f10cd8aba6e733665093865bcb
    with:
      java-version: '21'
      enable-dependency-check: false
