name: Security Reports

on:
  workflow_call:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  security:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-security-reports.yml@09ed978b979f1362cbbb3d9287aa06ddaa130bfc
    with:
      java-version: '21'
      enable-dependency-check: false
