name: Test release registration

on:
  workflow_dispatch:
    inputs:
      octopus-repository:
        type: string
        required: true
      release-version:
        type: string
        required: true

permissions:
  contents: read

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-register-release.yml@8dad627bc0be42f10cd8aba6e733665093865bcb
    with:
      octopus-repository: ${{ inputs.octopus-repository }}
      release-version:  ${{ inputs.release-version }}
    secrets: inherit
