name: Test check artifact and register release

on: workflow_dispatch

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-check-and-register-release.yml@06817836952f86617353adb578677f9ef94f0096
    with:
      artifact-pattern: "octopus-test/_VER_/octopus-test-_VER_.jar"
    secrets: inherit
